development:
  adapter: postgresql
  encoding: unicode
  database: snap_app_development
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: snap_app_test
  pool: 5
  host: localhost
  username: action
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: snap_app_production
  pool: 5
  host: localhost
  username: action
  password: